# Generated by Django 3.1.1 on 2020-09-15 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500000)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(auto_now=True)),
                ('mood_after', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mood_after', to='writeBrain.mood')),
                ('mood_before', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mood_before', to='writeBrain.mood')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='writeBrain.story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
            },
        ),
    ]
